import Image from "next/image";
import Link from "next/link";
import { BriefcaseBusiness, CalendarCheck, CircleDollarSign, FileUser } from "lucide-react";
import { StatCard } from "@/components/stat-card";
import { StatusPill } from "@/components/status-pill";

export default function DashboardPage() {
  const schedule = [["08:00", "A. Morgan", "Patio consultation", "Nico D.", "Confirmed", "/images/patio.jpg"], ["10:30", "Mia Chen", "Driveway prep", "Crew A", "In progress", "/images/driveway.jpg"], ["14:00", "N. Patel", "Deck measure", "Nico D.", "Scheduled", "/images/deck.jpg"]];
  return <div className="portal-page"><section className="kpi-grid"><StatCard label="New leads" value="14" trend="↑ 18% this month" icon={FileUser} /><StatCard label="Site visits" value="6" trend="2 awaiting confirmation" icon={CalendarCheck} tone="blue" /><StatCard label="Active jobs" value="9" trend="3 due this week" icon={BriefcaseBusiness} tone="amber" /><StatCard label="Open invoices" value="$28.4k" trend="1 overdue" icon={CircleDollarSign} tone="red" /></section><div className="dashboard-grid"><section className="panel pipeline-panel"><div className="panel-heading"><h2>Estimate pipeline</h2><Link href="/directors-ai-workspace/leads">View all leads →</Link></div><div className="pipeline-bars">{[["New", 14, 100], ["Qualified", 9, 72], ["Site visit", 6, 52], ["Estimate sent", 4, 38], ["Won", 3, 28]].map(([label, count, height]) => <div key={label}><span style={{ height: `${height}%` }} /><strong>{count}</strong><small>{label}</small></div>)}</div></section><section className="panel attention-panel"><div className="panel-heading"><h2>AI attention queue</h2><span className="status">3</span></div>{[["DG-1048", "Missing site details", "/images/patio.jpg"], ["DG-1042", "Draft reply ready", "/images/driveway.jpg"], ["DG-1033", "Follow-up due", "/images/deck.jpg"]].map(([id, note, image]) => <Link href={`/directors-ai-workspace/leads/${id}`} key={id}><Image src={image} alt="" width={42} height={42} /><span><strong>{id}</strong><small>{note}</small></span></Link>)}<Link className="button secondary" href="/directors-ai-workspace/ai">Open AI workspace</Link></section></div><section className="panel table-panel"><div className="panel-heading"><div><h2>Today&apos;s schedule</h2><span>Thursday, August 20</span></div><Link className="button primary small" href="/directors-ai-workspace/jobs">New job</Link></div><div className="responsive-table"><table><thead><tr><th>Time</th><th>Customer</th><th>Service</th><th>Crew</th><th>Status</th><th>Action</th></tr></thead><tbody>{schedule.map(([time, customer, service, crew, status, image]) => <tr key={time}><td data-label="Time"><strong>{time}</strong></td><td data-label="Customer">{customer}</td><td data-label="Service"><Image src={image} alt="" width={34} height={34} />{service}</td><td data-label="Crew">{crew}</td><td data-label="Status"><StatusPill>{status}</StatusPill></td><td data-label="Action"><Link className="text-link" href="/directors-ai-workspace/schedule">Open</Link></td></tr>)}</tbody></table></div></section></div>;
}
